#!/usr/bin/env bash
# Updates hostfile to change localhost to 127.0.0.2 and facebook.com to 8.8.8.8
# (To be run in Docker container; else revert hostfile back)
# https://web.archive.org/web/20171117023601/http://blog.jonathanargentiero.com/docker-sed-cannot-rename-etcsedl8ysxl-device-or-resource-busy/

printf "127.0.0.2\t\tlocalhost\n" > ~/change_home
printf "8.8.8.8\t\tfacebook.com\n" >> ~/change_home
cp -f ~/change_home /etc/hosts
